version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database_name   

      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password   

    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_database_name
      POSTGRES_USER: your_postgres_user   

    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data